### PR TITLE
Escape quotes in db comments and defaults

### LINKED ISSUE #16: Quotes in database comments & defaults not properly escaped
A column with a comment that contains a single quote (apostrophe) is not escaped resulting in:
```
'first_name' => $this->string(255)->comment('User's first name'),
'last_name' => $this->string(255)->comment('User's last name'),
```
Obviously, this should look like:
```
'first_name' => $this->string(255)->comment('User\'s first name'),
'last_name' => $this->string(255)->comment('User\'s last name'),
```

### PR DESCRIPTION
**Pull request by MarcoMoreno**
Fixes #16

### CODE REVIEW

**Comment by bizley** [comment]
Should we use `addslashes()` here or just `str_replace()` looking for `'`? `addslashes()` escapes more than just that.

**Comment by MarcoMoreno** [comment]
Yeah, I think you're right.  I didn't look into it too closely, but saw that Gii uses `addslashes()` for similar functionality.  However, I now see that an extraneous backslash is inserted into the comments for a double quote and a backslash.

Turns out though that I can't fully test this because `migrate` is horribly broken if `comment()` contains a string with a single quote so I'll have to submit a bug report for that.

In any case, I'll submit an update to use `str_replace()` instead so that at least the php code is syntactically correct.

**Comment by MarcoMoreno** [comment]
I made the change and issued a new pull request...though now I'm not sure that was needed.  Still figuring out github.

**Comment by MarcoMoreno** [comment]
BTW, I created an [issue for `migrate`](https://github.com/yiisoft/yii2/issues/15866)

**Comment by bizley** [comment]
Closed in favour of #18

**Pull request closed without merging**
